name: Run ox_task Daily

on:
  schedule:
    # Run at 8:00 AM UTC every day
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-ox-task:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Adjust version as needed
    
    - name: Install uv
      run: pip install uv
    
    - name: Install ox_task project
      run: |
        uv pip install --system git+https://github.com/emin63/ox_task.git
    
    - name: Run ox_task
      env:
        FROM_EMAIL: ${{ secrets.GMAIL_FROM_SECRET }}
        GMAIL_APP_PASSWD: ${{ secrets.GMAIL_APP_PASSWD }}
      run: |
        ox_task run tasks.json